### ISSUE TITLE
Property 'dir' does not exist on type 'typeof Deno

### ISSUE THREAD

**Issue by molvqingtai** [denodep/dep#2]
deno: v1.1.2
deno-dep: v0.2.2

When I run any command using dep, I will get this error

```shell
Check file:///usr/local/Cellar/deno-dep/0.2.2/libexec/lib/cli.ts
error: Uncaught TypeError: TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
 const dirhome = Deno.dir('home')
                      ~~~
    at file:///usr/local/Cellar/deno-dep/0.2.2/libexec/lib/store.ts:4:23

TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
 const dircache = !dirhome && Deno.dir('cache')
                                   ~~~
    at file:///usr/local/Cellar/deno-dep/0.2.2/libexec/lib/store.ts:5:36

TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
 	outputDir: Deno.dir('tmp')
 	                ~~~
    at file:///usr/local/Cellar/deno-dep/0.2.2/libexec/lib/commands/publish.ts:104:19

Found 3 errors.
```

**Comment by acathur** [comment]
OMG, `Deno.dir` has been removed (deno [#6385](https://github.com/denoland/deno/pull/6385)). Working on it...

**Comment by acathur** [comment]
Fixed. [`v0.2.3`](https://github.com/denodep/dep/releases/tag/v0.2.3)
